spring:
  application:
    name: backend-app
  datasource:
    url: jdbc:postgresql://postgres:5432/backend-app
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # options: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
